src/Models/ErrorViewModel.cs
using System;

namespace Kronos.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Models/Expense.cs
using System;
using System.ComponentModel.DataAnnotations;
using Kronos.Web.Database;

namespace Kronos.Web.Models
{

    public class AddExpenseModel
    {
        [Required]
        public DateTime Date { get; set; }
        [Required]
        public decimal Amount { get; set; }
        [Required]
        public string InvoiceNumber { get; set; }
        [Required]
        public int CategoryId { get; set; }
        public string Description { get; set; }
    }

    public class ExpenseListItem
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public string Description { get; set; }
        public string CategoryName { get; set; }
        public decimal Amount { get; set; }
    }

    public class UserLoginModel
    {
        [Required]
        public string Username { get; set; }
        [Required]
        public string Password { get; set; }
    }

    public class UserInfo
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public UserType Type { get; set; }
    }

}

src/Controllers/ExpenseController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Session;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Kronos.Web.Models;
using Kronos.Web.Database;

namespace Kronos.Web.Controllers
{
    public class ExpenseController : Controller
    {
        private readonly ILogger<ExpenseController> _logger;
        private readonly IDB _DB;

        public ExpenseController(ILogger<ExpenseController> logger, IDB db)
        {
            _logger = logger;
						_DB = db;
        }

				[HttpGet]
        public IActionResult MyExpenses() {
					//TODO: use authentication attributes
					int? userId = HttpContext.Session.GetInt32("UserId");
					if (!userId.HasValue)
						return Redirect("/User/Login");
					var expenses = _DB.ListExpenses(userId.Value);
					return View(expenses);
				}

				[HttpGet]
        public IActionResult Add() {
					//TODO: use authentication attributes
					int? userId = HttpContext.Session.GetInt32("UserId");
					if (!userId.HasValue)
						return Redirect("/User/Login");

					ViewData["Categories"] = _DB.ListCategories();
					return View(new AddExpenseModel{ Date = DateTime.Today });
				}

				[HttpPost]
        public IActionResult Add(AddExpenseModel expense) {
					//TODO: use authentication attributes
					int? userId = HttpContext.Session.GetInt32("UserId");
					if (!userId.HasValue || userId.Value == 0)
						return Redirect("/User/Login");

					if (expense.CategoryId == 0 && string.IsNullOrWhiteSpace(expense.Description))
						ModelState.AddModelError(nameof(expense.Description), "must have description if category is other");
					if (expense.Amount < 1)
						ModelState.AddModelError(nameof(expense.Amount), "must be at least $1");
					if (expense.Date > DateTime.Today)
						ModelState.AddModelError(nameof(expense.Date), "no time travelling");

					if (ModelState.IsValid) {
						_DB.AddExpense(userId.Value, expense);
						return Redirect("/Expense/MyExpenses");
					}

					ViewData["Categories"] = _DB.ListCategories();
					return View(expense);
				}
				
    }
}

src/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Kronos.Web.Models;

namespace Kronos.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Session;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Kronos.Web.Models;
using Kronos.Web.Database;

namespace Kronos.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly ILogger<UserController> _logger;
        private readonly IDB _DB;

        public UserController(ILogger<UserController> logger, IDB db)
        {
            _logger = logger;
            _DB = db;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View(new UserLoginModel());
        }

        [HttpPost]
        public IActionResult Login(UserLoginModel login)
        {
            if (!ModelState.IsValid)
            {
                return View(login);
            }
            var user = _DB.ValidateLogin(login.Username, login.Password);

            if (user != null)
            {
                HttpContext.Session.SetInt32("UserId", user.Id);
                HttpContext.Session.SetString("Username", user.Username);
                HttpContext.Session.SetInt32("UserType", (int)user.Type);
                return Redirect("/Expense/MyExpenses");
            }
            ModelState.AddModelError(string.Empty, "Invalid username or password");
            return View(login);
        }

    }
}

src/Views/Expense/Add.cshtml
@model AddExpenseModel
@{
    ViewData["Title"] = "Add Expense";
		List<SelectListItem> Categories = (List<SelectListItem>)ViewData["Categories"];
}

<h1>Add Expense</h1>
<form method="post">
	<div class="form-group">
		<label asp-for="Date"></label>
		<input asp-for="Date" class="form-control" type="date" />
		<span asp-validation-for="Date" class="text-danger"></span>
	</div>
	<div class="form-group">
			<label asp-for="InvoiceNumber">Invoice Number</label>
			<input asp-for="InvoiceNumber" class="form-control" />
			<span asp-validation-for="InvoiceNumber" class="text-danger"></span>
	</div>
	<div class="form-group">
			<label asp-for="CategoryId">Category</label>
			<select asp-for="CategoryId" asp-items="Categories">
			</select>
			<span asp-validation-for="CategoryId" class="text-danger"></span>
	</div>
	<div class="form-group">
			<label asp-for="Description">Category (if other)</label>
			<input asp-for="Description" class="form-control" />
			<span asp-validation-for="Description" class="text-danger"></span>
	</div>
	<div class="form-group">
			<label asp-for="Amount"></label>
			<input asp-for="Amount" class="form-control" />
			<span asp-validation-for="Amount" class="text-danger"></span>
	</div>

	<div class="form-group">
		<button type="submit" class="btn btn-primary">Add</button>
	</div>
</form>

src/Views/Expense/MyExpenses.cshtml
@model List<ExpenseListItem>
@using System.Text.Json
@{
    ViewData["Title"] = "My Expenses";
}

<div class="text-center">
	<h1 class="display-4">My Expenses</h1>

	<table class="table">
		<thead class="thead-dark">
			<tr>
				<th scope="col">Date</th>
				<th scope="col">Amount</th>
				<th scope="col">Category</th>
				<th scope="col">Description</th>
				<th><a class="btn btn-primary" href="/Expense/Add" role="Add">Add</a></th>
			</tr>
		</thead>
		<tbody>
			@foreach(var expense in Model) {
				<tr>
					<td>@expense.Date</td>
					<td>@expense.Amount</td>
					<td>@expense.CategoryName</td>
					<td>@expense.Description</td>
				</tr>
			}
		</tbody>
	</table>

src/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kronos.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Expense" asp-action="MyExpenses">Kronos.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                        </li>
                        <li class="nav-item">
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Kronos.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/Views/User/Login.cshtml
@model UserLoginModel
@{
    ViewData["Title"] = "Home Page";
}
<h1>Login</h1>
<form method="post">
	<div class="form-group">
		<label asp-for="Username" class="col-sm-2 col-form-label"></label>
		<input asp-for="Username" class="form-control" />
		<span asp-validation-for="Username" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Password" class="col-sm-2 col-form-label"></label>
		<input asp-for="Password" class="form-control" />
		<span asp-validation-for="Password" class="text-danger" type="password"></span>
	</div>
	<div class="form-group">
		<button type="submit" class="btn btn-primary">Sign in</button>
	</div>
	<h1>Available Logins</h1>

	<ul>
		<li>emp1/emp1</li>
		<li>man1/man1</li>
		<li>acc1/acc1</li>
</form>